[profile.default]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = true
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "./out" },
    { access = "read", path = "./script" },
]
gas_limit = "300000000"
bytecode_hash = "none"
allow_internal_expect_revert = true
exclude = [
    "lib/hookmate/node_modules/**/*",
    "lib/*/test/**/*",
    "lib/*/script/**/*",
]

[profile.default.fuzz]
runs = 1000
seed = "0x4444"

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/qrKOxN0aM6ljkPTJMQc7xks3CXqi9jAL"
holesky = "https://ethereum-holesky-rpc.publicnode.com"
mainnet = "https://ethereum-rpc.publicnode.com"
anvil = "http://localhost:8545"
